"use client";
import Link from "next/link";
import ExternalContacts from "../components/external-contacts";
import DoctorAvatar from "../components/doctor-avatar";
import { useEffect,useState } from "react";
import { Search, MapPin, Phone, Sparkles, ArrowUpRight } from "lucide-react";
import { supabase } from "../lib/supabase";
import { Reviews } from "../components/reviews";
type Result={registered:{id:string;name:string;photoPath:string|null;crm:string;clinicId:string|null;clinicName:string;address:string;specialtyId:string|null}[];external:{id:string;name:string;address:string;phone:string;mapsUrl:string;website:string;attributions:{provider?:string;providerUri?:string}[]}[];notices:string[];aiUsed:boolean;specialty:string|null};
const safeUrl=(url:string)=>/^https?:\/\//i.test(url)?url:"#";
export default function Discover(){const [query,setQuery]=useState("");const [city,setCity]=useState("");const [ai,setAi]=useState(false);const [external,setExternal]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [result,setResult]=useState<Result|null>(null);const [reviewId,setReviewId]=useState("");
useEffect(()=>{void(async()=>{const {data:{user}}=await supabase.auth.getUser();if(user){const {data}=await supabase.from("profiles").select("address_city").eq("id",user.id).maybeSingle();if(data?.address_city)setCity(data.address_city);}})();},[]);
async function search(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setResult(null);try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Entre na sua conta para buscar profissionais.");const response=await fetch("/api/discovery",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({query,city,useAI:ai,includeExternal:external})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Busca indisponível.");setResult(data);}catch(e){setError(e instanceof Error?e.message:"Falha na busca.");}finally{setBusy(false);}}
return <main className="min-h-screen bg-mn-sand px-5 py-10 sm:px-8"><div className="mx-auto max-w-6xl"><section className="relative overflow-hidden rounded-2xl bg-mn-teal px-6 py-10 text-white sm:p-12"><div className="absolute -right-16 -top-24 h-80 w-80 rounded-full border-[50px] border-white/5"/><p className="relative text-xs font-semibold uppercase tracking-[.2em] text-mn-sage-light">Cuidado perto de você</p><h1 className="relative mt-4 max-w-2xl text-4xl font-semibold tracking-tight sm:text-5xl">Encontre seu próximo<br/>profissional de confiança.</h1><p className="relative mt-5 max-w-xl text-sm leading-7 text-white/75">Busque por especialidade ou nome. Agende com profissionais da MediNexus ou encontre contatos na sua região.</p></section>
<form onSubmit={search} className="mn-panel relative mx-3 -mt-5 space-y-4 sm:mx-8"><div className="grid items-end gap-4 md:grid-cols-[1fr_1fr_auto]"><label className="text-sm font-semibold">Especialidade ou profissional<input required minLength={2} maxLength={180} className="mn-input mt-2" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex.: cardiologia"/></label><label className="text-sm font-semibold">Cidade<input required minLength={2} maxLength={100} className="mn-input mt-2" value={city} onChange={e=>setCity(e.target.value)} placeholder="Ex.: Rio de Janeiro"/></label><button className="mn-button" disabled={busy}><Search size={18}/>{busy?"Buscando…":"Encontrar"}</button></div><div className="flex flex-wrap gap-5 text-sm"><label className="flex gap-2"><input type="checkbox" checked={ai} onChange={e=>setAi(e.target.checked)}/><Sparkles size={17}/>Interpretar especialidade com IA</label><label className="flex gap-2"><input type="checkbox" checked={external} onChange={e=>setExternal(e.target.checked)}/>Incluir contatos do Google Maps</label></div>{(ai||external)&&<p className="text-xs text-slate-500">Ao ativar, o termo de busca será consultado no serviço escolhido; a cidade também será enviada ao Google Maps. Não informe sintomas ou dados pessoais.</p>}</form>
{error&&<p role="alert" className="mt-6 rounded-2xl bg-red-50 p-4 text-red-800">{error}</p>}{result&&<div className="mt-8 space-y-6">{result.notices.map(n=><p role="status" key={n} className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{n}</p>)}<div className="flex justify-between"><h2 className="text-xl font-semibold">Agende pela MediNexus</h2><span className="text-sm text-slate-500">{result.registered.length} resultado(s)</span></div>{result.aiUsed&&<p className="text-sm text-mn-purple">Especialidade interpretada: {result.specialty||"nenhuma especialidade explícita"}</p>}<div className="grid gap-4 md:grid-cols-2">{result.registered.map(d=><article key={d.id} className="mn-panel"><p className="mn-eyebrow">Na MediNexus</p><DoctorAvatar path={d.photoPath} name={d.name}/><h3 className="mt-2 text-xl font-semibold">{d.name}</h3><p className="mt-1 text-xs text-slate-500">CRM {d.crm}</p><p className="mt-4 text-sm font-medium">{d.clinicName}</p><p className="mt-1 flex gap-2 text-sm text-slate-500"><MapPin size={16}/>{d.address}</p><div className="mt-5 flex flex-wrap gap-3"><Link className="mn-button" href={`/busca?${d.clinicId?`clinicId=${d.clinicId}&`:""}${d.specialtyId?`specialtyId=${d.specialtyId}`:""}`}>Consultar horários</Link><button className="mn-button-secondary" onClick={()=>setReviewId(reviewId===d.id?"":d.id)}>Avaliações</button></div>{reviewId===d.id&&<div className="mt-4"><Reviews kind="doctor" targetId={d.id}/></div>}</article>)}</div>{!result.registered.length&&<div className="mn-panel text-sm text-slate-500">Nenhum profissional cadastrado encontrado para esta busca. Experimente o nome da especialidade ou outra cidade.</div>}{result.external.length>0&&<><h2 className="pt-4 text-xl font-semibold">Outros contatos na região</h2><p className="text-sm text-slate-500">Informações fornecidas pelo Google Maps. Contato direto; sem agendamento pelo aplicativo nestes resultados.</p><div className="grid gap-4 md:grid-cols-2">{result.external.map(d=><article key={d.id} className="mn-panel"><p className="mn-eyebrow">Contato externo · Google Maps</p><h3 className="text-xl font-semibold">{d.name}</h3><p className="mt-3 text-sm text-slate-500">{d.address}</p><div className="mt-5 flex flex-wrap gap-3">{d.phone&&<a className="mn-button-secondary" href={`tel:${d.phone.replace(/[^+0-9]/g,"")}`}><Phone size={16}/>{d.phone}</a>}{d.mapsUrl&&<a className="mn-button-secondary" href={safeUrl(d.mapsUrl)} target="_blank" rel="noopener noreferrer">Google Maps<ArrowUpRight size={16}/></a>}{d.website&&<a className="mn-button-secondary" href={safeUrl(d.website)} target="_blank" rel="noopener noreferrer">Site</a>}</div>{d.attributions.map((a,i)=><p className="mt-2 text-xs text-slate-500" key={i}>{a.providerUri?<a href={safeUrl(a.providerUri)} target="_blank" rel="noopener noreferrer">{a.provider}</a>:a.provider}</p>)}</article>)}</div></>}</div>}
<ExternalContacts/><div className="mt-8 flex gap-4 text-sm"><Link className="text-mn-teal underline" href="/busca">Busca por disponibilidade</Link><Link className="text-mn-teal underline" href="/perfil">Atualizar meu endereço</Link></div></div></main>;}
