"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useAuth } from "../components/auth-provider";
import { Reviews } from "../components/reviews";
import { supabase } from "../lib/supabase";
function one<T>(value:T|T[]|null|undefined):T|null{return Array.isArray(value)?value[0]??null:value??null;}
export default function ReviewsPage(){const {access,loading}=useAuth();const [mine,setMine]=useState<{id:string;target_kind:string;rating:number;comment:string;anonymous:boolean;appointments:{doctors:{name:string}|{name:string}[]|null;clinics:{trade_name:string}|{trade_name:string}[]|null}|{doctors:{name:string}|{name:string}[]|null;clinics:{trade_name:string}|{trade_name:string}[]|null}[]|null}[]>([]);const [error,setError]=useState("");useEffect(()=>{if(!access.userId)return;void supabase.from("care_reviews").select("id,target_kind,rating,comment,anonymous,appointments(doctors(name),clinics(trade_name))").eq("author_id",access.userId).order("created_at",{ascending:false}).then(({data,error})=>{setMine(data||[]);if(error)setError("Não foi possível carregar suas avaliações.");});},[access.userId]);if(loading)return <p className="p-8">Carregando…</p>;if(!access.userId)return <main className="app-shell py-16"><h1 className="text-3xl font-semibold">Avaliações</h1><Link className="mn-button mt-6" href="/login">Entrar na minha conta</Link></main>;
return <main className="app-shell space-y-6 py-10"><div className="mn-panel"><p className="mn-eyebrow">Sua experiência importa</p><h1 className="text-3xl font-semibold">Avaliações</h1><p className="mt-3 text-sm leading-6 text-slate-500">Avalie atendimentos concluídos pela tela de consultas. Seu nome pode ficar oculto nas avaliações públicas de médicos e clínicas.</p><Link className="mn-button mt-5" href={access.role==="doctor"?"/medico/consultas":access.role==="clinic"?"/clinica/solicitacoes":"/solicitacoes"}>Ver consultas</Link></div>{access.id&&(access.role==="doctor"||access.role==="clinic")&&<Reviews kind={access.role} targetId={access.id}/>}<section className="mn-panel"><h2 className="text-xl font-semibold">Avaliações que você enviou</h2>{error&&<p role="alert" className="mt-4 text-sm">{error}</p>}{!error&&!mine.length&&<p className="mt-4 text-sm text-slate-500">Você ainda não enviou avaliações.</p>}<div className="divide-y divide-mn-border">{mine.map(r=><article key={r.id} className="py-4"><p className="text-sm font-semibold">{r.target_kind==="doctor"?"Médico":r.target_kind==="clinic"?"Clínica":"Paciente · visível apenas na área médica"} · {r.rating}/5</p><p className="mt-2 text-sm">Médico: {one(one(r.appointments)?.doctors)?.name || "Não informado"}</p><p className="text-sm">Clínica: {one(one(r.appointments)?.clinics)?.trade_name || "Consultório / não informada"}</p><p className="mt-1 text-xs text-slate-500">{r.anonymous?"Nome oculto":"Primeiro nome visível"}</p><p className="mt-2 text-sm">{r.comment}</p></article>)}</div></section></main>;}
