"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
export default function Recovery(){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[repeat,setRepeat]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[updating,setUpdating]=useState(false),[ready,setReady]=useState(false);
 useEffect(()=>{let alive=true;const update=new URLSearchParams(window.location.search).get('update')==='1';void supabase.auth.getSession().then(({data})=>{if(alive){setUpdating(update);setReady(!!data.session);}});const {data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{if(alive)setReady(!!session);});return()=>{alive=false;subscription.unsubscribe();};},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{
  if(updating){if(!ready)throw new Error("Abra um link de recuperação válido enviado ao seu e-mail.");if(password.length<10||password!==repeat)throw new Error("Use pelo menos 10 caracteres e repita a mesma senha.");const r=await supabase.auth.updateUser({password});if(r.error)throw new Error("Não foi possível alterar a senha. Solicite um novo link.");await supabase.auth.signOut();setPassword("");setRepeat("");setMessage("Senha atualizada. Entre novamente com sua nova senha.");setUpdating(false);}
  else{const r=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${window.location.origin}/recuperar-conta?update=1`});if(r.error)throw new Error("Não foi possível enviar agora. Aguarde e tente novamente.");setMessage("Se existir uma conta com esse e-mail, você receberá um link para redefinir a senha. Confira também o spam.");}
 }catch(e){setMessage(e instanceof Error?e.message:"Não foi possível continuar.");}finally{setBusy(false);}}
 return <main className="app-shell py-12"><section className="mn-panel mx-auto max-w-lg"><h1 className="text-2xl font-semibold">{updating?"Criar uma nova senha":"Recuperar acesso"}</h1><form onSubmit={submit} className="mt-6 space-y-4">{updating?<><label className="block text-sm">Nova senha<input className="mn-input mt-2" type="password" autoComplete="new-password" minLength={10} required value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="block text-sm">Repita a nova senha<input className="mn-input mt-2" type="password" autoComplete="new-password" minLength={10} required value={repeat} onChange={e=>setRepeat(e.target.value)}/></label>{!ready&&<p className="text-sm">Abra o link recebido por e-mail. Se ele expirou, solicite outro.</p>}</>:<label className="block text-sm">E-mail da conta<input className="mn-input mt-2" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}<button className="mn-button" disabled={busy||(updating&&!ready)}>{busy?"Aguarde…":updating?"Salvar nova senha":"Enviar link de recuperação"}</button></form>{message&&<p role="status" className="mt-4 text-sm">{message}</p>}<div className="mt-6 flex gap-4 text-sm"><Link href="/login" className="underline">Voltar ao login</Link>{updating&&<Link href="/recuperar-conta" className="underline" onClick={()=>{setUpdating(false);setMessage("");}}>Solicitar outro link</Link>}</div></section></main>;
}
