import {useEffect,useState} from "react";
import {Image,ScrollView,Text,TextInput,View} from "react-native";
import {supabase} from "./supabase";
import {Button,Toggle,ui} from "./ui";
type Match={doctor_id:string;doctor_name:string;photo_path:string;clinic_name:string;start_at:string;match_kind:string;appointment_mode:string;coverage:string;private_price_cents:number|null};
const weekdays=["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"];
const when=(date:string)=>new Date(date).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"});
export default function AvailabilitySearch({userId,onBooked}:{userId:string;onBooked:()=>void}){
 const [specialties,setSpecialties]=useState<{id:string;name:string}[]>([]),[specialty,setSpecialty]=useState("");
 const [start,setStart]=useState(""),[end,setEnd]=useState(""),[from,setFrom]=useState("09:00"),[until,setUntil]=useState("12:00"),[days,setDays]=useState<number[]>([1,2,3,4,5]),[radius,setRadius]=useState("50"),[privateMode,setPrivateMode]=useState(false);
 const [matches,setMatches]=useState<Match[]>([]),[searchId,setSearchId]=useState(""),[searchPrivate,setSearchPrivate]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[accepted,setAccepted]=useState<Record<string,{nearby?:boolean;private?:boolean}>>({});
 useEffect(()=>{let alive=true;void supabase.from("specialties").select("id,name").order("name").then(r=>{if(alive){setSpecialties(r.data||[]);if(r.error)setMessage("Não foi possível carregar as especialidades.");}});return()=>{alive=false;};},[]);
 async function search(){setBusy(true);setMessage("");setMatches([]);setSearchId("");setAccepted({});try{
  if(!specialty||!days.length||!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end)||!/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(from)||!/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(until)||from>=until||!Number.isInteger(Number(radius))||Number(radius)<1||Number(radius)>500)throw new Error("Selecione especialidade e dias. Use datas AAAA-MM-DD, horários HH:MM e raio entre 1 e 500 km.");
  const pref=await supabase.from("patient_search_preferences").insert({patient_id:userId,specialty_id:specialty,preferred_start_date:start,preferred_end_date:end,max_radius_km:Number(radius),accepts_private_consultation:privateMode}).select("id").single();if(pref.error)throw new Error("Não foi possível salvar sua disponibilidade. Confira as datas.");
  const windows=await supabase.from("patient_search_time_windows").insert(days.map(weekday=>({search_preference_id:pref.data.id,weekday,start_time:from,end_time:until})));if(windows.error)throw new Error("Não foi possível salvar os horários.");
  const result=await supabase.rpc("match_patient_availability",{p_search_id:pref.data.id});if(result.error)throw new Error(result.error.message);setSearchId(pref.data.id);setSearchPrivate(privateMode);setMatches(result.data||[]);if(!result.data?.length)setMessage("Nenhum horário encontrado. Confira o endereço do perfil ou amplie o período e o raio.");else if(!result.data.some((m:Match)=>m.match_kind==='exact'))setMessage("Não há disponibilidade exata nesse período. Estas são as opções mais próximas; confirme se pode comparecer.");
 }catch(e){setMessage(e instanceof Error?e.message:"Busca indisponível.");}finally{setBusy(false);}}
 async function book(m:Match){setBusy(true);const r=await supabase.rpc("request_matched_appointment",{p_search_id:searchId,p_doctor_id:m.doctor_id,p_start_at:m.start_at,p_accept_nearby:accepted[m.doctor_id]?.nearby===true,p_accept_private:accepted[m.doctor_id]?.private===true});if(r.error)setMessage(r.error.message);else{setMatches([]);onBooked();}setBusy(false);}
 return <View style={{gap:14}}><Text style={ui.heading}>Quando você pode ir à consulta?</Text><Text style={ui.copy}>Informe seus dias e horários. Vamos encontrar os melhores encaixes na rede. Horários de Brasília.</Text><Text style={ui.label}>Especialidade</Text><ScrollView horizontal>{specialties.map(s=><View key={s.id} style={{marginRight:8}}><Button title={s.name} secondary={specialty!==s.id} disabled={busy} onPress={()=>setSpecialty(s.id)}/></View>)}</ScrollView>{([["Data inicial (AAAA-MM-DD)",start,setStart],["Data final (AAAA-MM-DD)",end,setEnd],["Posso ir a partir de (HH:MM)",from,setFrom],["Posso ficar até (HH:MM)",until,setUntil],["Raio de busca (km)",radius,setRadius]] as const).map(([label,value,change])=><View key={label}><Text style={ui.label}>{label}</Text><TextInput accessibilityLabel={label} style={ui.input} value={value} onChangeText={change} editable={!busy} maxLength={10}/></View>)}{weekdays.map((day,i)=><Toggle key={day} label={day} value={days.includes(i)} disabled={busy} onChange={v=>setDays(old=>v?[...old,i]:old.filter(d=>d!==i))}/>)}<Toggle label="Buscar consulta particular (desative para usar meu convênio)" value={privateMode} disabled={busy} onChange={setPrivateMode}/><Button title={busy?"Consultando…":"Encontrar encaixes"} disabled={busy} onPress={()=>void search()}/>{!!message&&<Text accessibilityRole="alert" style={ui.message}>{message}</Text>}{matches.map(m=>{const alternative=m.match_kind!=='exact',fallback=m.appointment_mode==='private'&&!searchPrivate,a=accepted[m.doctor_id]||{};return <View key={m.doctor_id} style={ui.panel}><Image accessibilityLabel={`Foto de ${m.doctor_name}`} source={{uri:supabase.storage.from('doctor-photos').getPublicUrl(m.photo_path).data.publicUrl}} style={{width:64,height:64,borderRadius:18}}/><Text style={ui.heading}>{m.doctor_name}</Text><Text style={ui.copy}>{m.clinic_name} · {when(m.start_at)}</Text><Text style={ui.copy}>{alternative?'Alternativa próxima':'Dentro da sua disponibilidade'}</Text><Text style={ui.copy}>{m.appointment_mode==='private'?`Particular · ${m.private_price_cents?`R$ ${(m.private_price_cents/100).toFixed(2)}`:'valor a confirmar'}`:m.coverage==='confirmation_required'?'Convênio: confirmação necessária':'Plano cadastrado aceito'}</Text>{alternative&&<Toggle label="Posso comparecer neste horário alternativo" value={a.nearby===true} onChange={v=>setAccepted(old=>({...old,[m.doctor_id]:{...old[m.doctor_id],nearby:v}}))}/>} {fallback&&<Toggle label="Aceito atendimento particular, pois meu plano não consta como aceito" value={a.private===true} onChange={v=>setAccepted(old=>({...old,[m.doctor_id]:{...old[m.doctor_id],private:v}}))}/>}<Button title="Solicitar este horário" disabled={busy||(alternative&&!a.nearby)||(fallback&&!a.private)} onPress={()=>void book(m)}/></View>;})}</View>;
}
