import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
test('patient availability: private/exact plan/manual coverage, nearest alternative, reserved slots and permissions',async()=>{
 const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 create table profiles(id uuid primary key,latitude double precision,longitude double precision);
 create table health_plans(id uuid primary key default gen_random_uuid(),name text,operator_name text,plan_type text);
 create table patients(id uuid primary key,default_health_plan_id uuid,health_plan_product_name text,health_plan_operator text);
 create table clinics(id uuid primary key,user_id uuid,created_by uuid,trade_name text,address_city text,address_state text,address_neighborhood text,latitude double precision,longitude double precision,is_active boolean,accepts_private_consultation boolean,base_private_price_cents integer);
 create table doctors(id uuid primary key,user_id uuid,clinic_id uuid,name text,crm text,crm_state text,address_city text,address_state text,address_neighborhood text,latitude double precision,longitude double precision,is_active boolean,accepts_private_consultation boolean,private_price_cents integer,average_consultation_minutes integer,doctor_completed boolean default false);
 create table clinic_members(clinic_id uuid,user_id uuid,member_role text,role text);
 create table doctor_specialties(doctor_id uuid,specialty_id uuid);
 create table clinic_health_plans(clinic_id uuid,health_plan_id uuid);
 create table doctor_health_plans(doctor_id uuid,health_plan_id uuid);
 create table doctor_availability(doctor_id uuid,weekday integer,day_of_week integer,start_time time,end_time time,is_active boolean,slot_minutes integer);
 create table patient_search_preferences(id uuid primary key,patient_id uuid,specialty_id uuid,preferred_start_date date,preferred_end_date date,preferred_clinic_id uuid,max_radius_km integer,accepts_private_consultation boolean);
 create table patient_search_time_windows(search_preference_id uuid,weekday integer,start_time time,end_time time);
 create table appointments(id uuid primary key default gen_random_uuid(),patient_id uuid,doctor_id uuid,clinic_id uuid,specialty_id uuid,requested_start_at timestamptz,requested_end_at timestamptz,confirmed_start_at timestamptz,confirmed_end_at timestamptz,status text,patient_confirmation_status text,appointment_mode text,auto_suggested boolean,appointment_duration_minutes integer);
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(name text,bucket_id text);
 create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;
 `);
 for(const name of ['20260917030000_doctor_photos.sql','20260917040000_patient_availability.sql','20260917050000_health_plan_catalog.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+name,'utf8'));
 const day=(await db.query("select ((now() at time zone 'America/Sao_Paulo')::date+2)::text as day")).rows[0].day;
 await db.exec(`insert into profiles values('${id(1)}',-22.9,-43.2),('${id(2)}',-22.9,-43.2);
 insert into patients(id) values('${id(1)}'),('${id(2)}');insert into health_plans(id) values('${id(20)}'),('${id(21)}');
 insert into clinics(id,user_id,trade_name,address_city,address_state,latitude,longitude,is_active,accepts_private_consultation,base_private_price_cents) values('${id(5)}','${id(6)}','Clínica','Rio','RJ',-22.9,-43.2,true,true,10000);
 insert into doctors(id,user_id,clinic_id,name,crm,crm_state,is_active,accepts_private_consultation,average_consultation_minutes) values('${id(3)}','${id(4)}','${id(5)}','Médico','123','RJ',true,true,30);
 insert into doctor_specialties values('${id(3)}','${id(10)}');
 insert into doctor_availability select '${id(3)}',n,n,'09:00','12:00',true,30 from generate_series(0,6)n;
 insert into patient_search_preferences values('${id(11)}','${id(1)}','${id(10)}','${day}','${day}',null,10,true);
 insert into patient_search_time_windows select '${id(11)}',extract(dow from '${day}'::date),'09:00','10:00';`);
 await db.query("select set_config('test.uid',$1,false)",[id(1)]);
 const match=()=>db.query('select * from match_patient_availability($1)',[id(11)]);
 assert.equal((await match()).rows.length,0,'Doctor without a photo is not bookable');
 await assert.rejects(db.query('select set_doctor_photo($1,$2)',[id(3),`${id(3)}/photo.jpg`]));
 await db.query("select set_config('test.uid',$1,false)",[id(4)]);
 await assert.rejects(db.query('select set_doctor_photo($1,$2)',[id(3),`${id(3)}/photo.jpg`]));
 await db.query('insert into storage.objects values($1,$2)',[`${id(3)}/photo.jpg`,'doctor-photos']);
 await db.query('select set_doctor_photo($1,$2)',[id(3),`${id(3)}/photo.jpg`]);
 await db.query("select set_config('test.uid',$1,false)",[id(1)]);
 assert.equal((await db.query("select count(*)::int n from health_plans where catalog_key is not null")).rows[0].n,15);
 const catalog=(await db.query("select id,name from health_plans where catalog_key='porto-ouro-pro-copar-q'")).rows[0];
 await db.query("update patients set default_health_plan_id=$1,health_plan_product_name='forged' where id=$2",[catalog.id,id(1)]);
 assert.equal((await db.query('select health_plan_product_name from patients where id=$1',[id(1)])).rows[0].health_plan_product_name,catalog.name);
 await db.query("update patients set default_health_plan_id=null,health_plan_product_name=null where id=$1",[id(1)]);
 let row=(await match()).rows[0];assert.equal(row.match_kind,'exact');assert.equal(row.appointment_mode,'private');assert.equal(row.difference_minutes,0);
 const first=row.start_at;
 await db.query("update patient_search_time_windows set start_time='14:00',end_time='15:00'");
 row=(await match()).rows[0];assert.equal(row.match_kind,'nearby');assert.equal(row.difference_minutes,150);
 await assert.rejects(db.query('select request_matched_appointment($1,$2,$3)',[id(11),id(3),row.start_at]));
 await db.query("update patient_search_time_windows set start_time='09:00',end_time='10:00'");
 await db.query(`update patients set default_health_plan_id=$1 where id=$2`,[id(20),id(1)]);
 await db.exec('update patient_search_preferences set accepts_private_consultation=false');
 row=(await match()).rows[0];assert.equal(row.appointment_mode,'private','Unaccepted catalog plan requires private fallback');
 await assert.rejects(db.query('select request_matched_appointment($1,$2,$3,true,false)',[id(11),id(3),row.start_at]));
 await db.query('insert into clinic_health_plans values($1,$2)',[id(5),id(20)]);
 row=(await match()).rows[0];assert.equal(row.coverage,'catalog_match');assert.equal(row.appointment_mode,'health_plan');
 await db.query('insert into doctor_health_plans values($1,$2)',[id(3),id(21)]);
 assert.equal((await match()).rows[0].appointment_mode,'private','Doctor acceptance restricts clinic coverage');
 await db.exec('delete from doctor_health_plans');
 await db.query("update patients set default_health_plan_id=null,health_plan_product_name='Outro plano' where id=$1",[id(1)]);
 row=(await match()).rows[0];assert.equal(row.coverage,'confirmation_required');
 const booking=(await db.query('select request_matched_appointment($1,$2,$3) as id',[id(11),id(3),row.start_at])).rows[0].id;
 assert.equal((await db.query('select coverage_status from appointments where id=$1',[booking])).rows[0].coverage_status,'confirmation_required');
 await assert.rejects(db.query("update appointments set coverage_status='accepted',status='confirmed' where id=$1",[booking]));
 await assert.rejects(db.query("update appointments set requested_start_at=requested_start_at+interval '10 hours' where id=$1",[booking]));
 assert.notEqual((await match()).rows[0].start_at,first,'A reservation is excluded without revealing another patient');
 await assert.rejects(db.query('select resolve_appointment_coverage($1,true)',[booking]));
 await db.query("select set_config('test.uid',$1,false)",[id(4)]);
 await db.query('select resolve_appointment_coverage($1,true)',[booking]);
 assert.equal((await db.query('select coverage_status from appointments where id=$1',[booking])).rows[0].coverage_status,'accepted');
 await db.query("select set_config('test.uid',$1,false)",[id(1)]);
 await db.query("update appointments set status='cancelled_by_patient' where id=$1",[booking]);
 await db.query("select set_config('test.uid',$1,false)",[id(2)]);await assert.rejects(match());
 await db.exec(`insert into doctors(id,user_id,name,crm,crm_state,is_active,accepts_private_consultation,average_consultation_minutes,latitude,longitude,address_city,address_state,private_price_cents) values('${id(31)}','${id(41)}','Autônomo','456','RJ',true,true,30,-22.9,-43.2,'Rio','RJ',12000);
 insert into doctor_specialties values('${id(31)}','${id(10)}');insert into doctor_availability select '${id(31)}',n,n,'09:00','12:00',true,30 from generate_series(0,6)n;`);
 await db.query('insert into storage.objects values($1,$2)',[`${id(31)}/photo.jpg`,'doctor-photos']);
 await db.query("select set_config('test.uid',$1,false)",[id(41)]);await db.query('select set_doctor_photo($1,$2)',[id(31),`${id(31)}/photo.jpg`]);
 await db.query("select set_config('test.uid',$1,false)",[id(1)]);
 const officeSlot=(await db.query('select * from get_doctor_booking_slots($1,$2)',[id(31),id(10)])).rows[0];assert.ok(officeSlot);assert.equal(officeSlot.clinic_id,null);
 await assert.rejects(db.query("insert into appointments(patient_id,doctor_id,specialty_id,status,appointment_mode,requested_start_at,requested_end_at) values($1,$2,$3,'pending','private',$4,$4::timestamptz+interval '1 minute')",[id(1),id(31),id(10),officeSlot.start_at]),'A client cannot forge a one-minute appointment');
 assert.ok((await db.query('select request_doctor_booking($1,$2,$3) as id',[id(31),id(10),officeSlot.start_at])).rows[0].id);
 }finally{await db.close();}
});
