import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
test('clinical history requires patient grant; AI is consent-gated, separately stored and reviewed',async()=>{
 const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 create table auth.users(id uuid primary key);create table patients(id uuid primary key);
 create table doctors(id uuid primary key,user_id uuid,name text,is_active boolean);
 create table appointments(id uuid primary key,patient_id uuid,doctor_id uuid,status text,confirmed_start_at timestamptz,created_at timestamptz default now());
 create table patient_preferences(patient_id uuid primary key);
 create table consultation_notes(id uuid primary key,appointment_id uuid,patient_id uuid,doctor_id uuid,subjective text,objective text,assessment text,plan text,summary text,private_notes text);
 create table medical_records(id uuid primary key,patient_id uuid);
 create table prescriptions(id uuid primary key,appointment_id uuid,patient_id uuid,doctor_id uuid,title text,content text,guidance text);
 create table medical_documents(id uuid primary key,appointment_id uuid,patient_id uuid,doctor_id uuid,title text,document_type text,plain_text text,issued_at timestamptz,status text,released_to_patient boolean,certification_required boolean);
 alter table medical_documents enable row level security;
 create policy certified_document_read_guard on medical_documents as restrictive for select using(false);
 -- Simulate legacy broad read policies: new restrictive guards must override them.
 create policy legacy_notes on consultation_notes for select using(true);
 create policy legacy_records on medical_records for select using(true);
 create policy legacy_prescriptions on prescriptions for select using(true);
 grant usage on schema auth to authenticated;grant select on doctors,appointments,consultation_notes,medical_records,prescriptions,medical_documents to authenticated;
 `);
 await db.exec(fs.readFileSync('supabase/migrations/20260917060000_clinical_summaries.sql','utf8'));
 await db.exec(`insert into auth.users values('${id(1)}'),('${id(2)}'),('${id(3)}');insert into patients values('${id(1)}');
 insert into doctors values('${id(20)}','${id(2)}','Doctor original',true),('${id(30)}','${id(3)}','Future doctor',true);
 insert into appointments(id,patient_id,doctor_id,status) values('${id(40)}','${id(1)}','${id(20)}','confirmed'),('${id(41)}','${id(1)}','${id(30)}','confirmed');
 insert into patient_preferences(patient_id) values('${id(1)}');
 insert into consultation_notes(id,appointment_id,patient_id,doctor_id,subjective,objective,assessment,plan,summary) values('${id(50)}','${id(40)}','${id(1)}','${id(20)}','Original',null,null,null,'Doctor summary');
 insert into medical_records values('${id(60)}','${id(1)}');
 insert into medical_documents values('${id(70)}','${id(40)}','${id(1)}','${id(20)}','Prescription','prescription','Original medicine',now(),'issued',true,true);
 update appointments set status='completed' where id='${id(40)}';`);
 assert.equal((await db.query('select * from claim_clinical_summary_job()')).rows.length,0);
 await db.exec('update patient_preferences set clinical_ai_consent=true');
 assert.equal((await db.query('select * from claim_clinical_summary_job()')).rows.length,1);
 assert.equal((await db.query('select * from claim_clinical_summary_job()')).rows.length,0);
 await db.exec(`insert into clinical_ai_summaries(id,appointment_id,patient_id,doctor_id,summary,source_hash,model) values('${id(80)}','${id(40)}','${id(1)}','${id(20)}','AI summary','hash','test');`);
 const login=async n=>{await db.exec('reset role');await db.query("select set_config('test.uid',$1,false)",[id(n)]);await db.exec('set role authenticated');};
 await db.exec("update consultation_notes set private_notes='Doctor only'");
 await login(3);
 await assert.rejects(db.query('select read_authorized_clinical_history($1)',[id(1)]));
 assert.equal((await db.query('select id,subjective from consultation_notes')).rows.length,0);
 assert.equal((await db.query('select * from medical_records')).rows.length,0);
 await assert.rejects(db.query('select review_clinical_summary($1)',[id(80)]));
 await login(1);
 assert.equal((await db.query('select * from clinical_ai_summaries')).rows.length,0,'Unreviewed AI is not patient-facing');
 await assert.rejects(db.query("insert into clinical_history_grants(patient_id,doctor_id,expires_at) values($1,$2,now()+interval '91 days')",[id(1),id(30)]));
 await db.query("insert into clinical_history_grants(patient_id,doctor_id,expires_at) values($1,$2,now()+interval '30 days')",[id(1),id(30)]);
 await login(3);
 assert.equal((await db.query('select id,subjective from consultation_notes')).rows.length,1);
 await assert.rejects(db.query('select private_notes from consultation_notes'));
 assert.equal((await db.query('select read_own_consultation_note($1) note',[id(40)])).rows[0].note,null);
 assert.equal((await db.query('select * from medical_documents')).rows.length,1);
 let history=(await db.query('select read_authorized_clinical_history($1) as history',[id(1)])).rows[0].history;
 assert.equal(history[0].ai_summaries.length,0);
 assert.equal(history[0].notes[0].subjective,'Original');
 await assert.rejects(db.query("update clinical_ai_summaries set summary='forged'"));
 await db.exec('reset role');await db.exec('update clinical_ai_summaries set source_revision=(select source_revision from clinical_summary_jobs limit 1)');
 await login(2);assert.equal((await db.query('select read_own_consultation_note($1) note',[id(40)])).rows[0].note.private_notes,'Doctor only');await db.query('select review_clinical_summary($1)',[id(80)]);
 await login(1);
 assert.equal((await db.query('select * from clinical_ai_summaries')).rows[0].summary,'AI summary');
 await db.query('delete from clinical_history_grants where patient_id=$1',[id(1)]);
 await login(3);await assert.rejects(db.query('select read_authorized_clinical_history($1)',[id(1)]));
 assert.equal((await db.query('select * from medical_documents')).rows.length,0);
 await login(2);assert.equal((await db.query('select id,subjective from consultation_notes')).rows[0].subjective,'Original');
 await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from clinical_history_access_log')).rows[0].n,1);
 await db.exec("update clinical_summary_jobs set status='done'; update consultation_notes set plan='Follow-up original' where id='"+id(50)+"'");
 assert.equal((await db.query('select status,source_revision from clinical_summary_jobs')).rows[0].status,'queued');
 assert.equal((await db.query('select summary from clinical_ai_summaries')).rows[0].summary,'AI summary','Original update does not rewrite old AI summary');
 await db.exec("update clinical_ai_summaries set reviewed_at=null,reviewed_by=null");
 await login(2);await assert.rejects(db.query('select review_clinical_summary($1)',[id(80)]),'Stale source cannot be approved');await db.exec('reset role');
 await db.exec(fs.readFileSync('supabase/migrations/20260917090000_legacy_prescriptions_readonly.sql','utf8'));
 await assert.rejects(db.query('insert into prescriptions(id) values($1)',[id(90)]));

 }finally{await db.close();}
});
