import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { PGlite } from "@electric-sql/pglite";
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
test("database protects signatures, anonymous reviews and message claims",async()=>{
 const db=new PGlite();
 try{
 await db.exec(`
 create role anon; create role authenticated; create role service_role;
 create schema auth; create schema storage;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 create function auth.role() returns text language sql stable as $$select current_setting('test.role',true)$$;
 create table auth.users(id uuid primary key);
 create table public.profiles(id uuid primary key,full_name text);
 create table public.patients(id uuid primary key,full_name text,cpf text,birth_date date,phone text,health_plan_operator text);
 create table public.doctors(id uuid primary key,user_id uuid,name text,crm text,crm_state text,is_active boolean,clinic_id uuid,average_consultation_minutes integer,accepts_private_consultation boolean);
 create table public.doctor_availability(doctor_id uuid,is_active boolean,weekday integer,day_of_week integer,start_time time,end_time time,slot_minutes integer);
 create table public.clinics(id uuid primary key,trade_name text,legal_name text,address_street text,address_number text,address_complement text,address_city text,address_state text,address_neighborhood text,is_active boolean,accepts_private_consultation boolean);
 create table public.specialties(id uuid primary key,name text);
 create table public.doctor_specialties(id uuid default gen_random_uuid(),doctor_id uuid,specialty_id uuid);
 create table public.appointments(id uuid primary key default gen_random_uuid(),doctor_id uuid,patient_id uuid,clinic_id uuid,status text,confirmed_start_at timestamptz,requested_start_at timestamptz,requested_end_at timestamptz,confirmed_end_at timestamptz,specialty_id uuid,patient_confirmation_status text,appointment_mode text,auto_suggested boolean,appointment_duration_minutes integer);
 create table public.medical_documents(id uuid primary key default gen_random_uuid(),doctor_id uuid,patient_id uuid,clinic_id uuid,appointment_id uuid,created_by uuid,doctor_name text,doctor_crm text,doctor_crm_state text,content jsonb,status text,signature_status text,signature_provider text,signature_validation_url text,signed_at timestamptz,signed_pdf_url text,document_hash text,released_to_patient boolean,released_at timestamptz,issued_at timestamptz,cancelled_at timestamptz,cancelled_reason text,updated_at timestamptz);
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid,name text,bucket_id text);
 create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;
 `);
 for(const file of ["20260916020000_professional_documents.sql","20260916030000_profiles_reviews.sql","20260916040000_notifications.sql","20260916050000_discovery_quota.sql","20260916060000_doctor_offices.sql","20260916070000_native_booking.sql"])await db.exec(fs.readFileSync("supabase/migrations/"+file,"utf8"));
 await db.exec(`insert into auth.users values('${id(1)}'),('${id(2)}'),('${id(3)}');insert into profiles values('${id(1)}','Médico Um'),('${id(2)}','Paciente Privado'),('${id(3)}','Outro Médico');insert into patients values('${id(2)}','Paciente Privado',null,null,null,null);insert into doctors(id,user_id,name,crm,crm_state,is_active) values('${id(11)}','${id(1)}','Médico Um','123','RJ',true),('${id(13)}','${id(3)}','Outro Médico','456','RJ',true);insert into clinics(id,trade_name) values('${id(20)}','Clínica');insert into specialties values('${id(30)}','Cardiologia');insert into appointments(id,doctor_id,patient_id,clinic_id,status,confirmed_start_at,requested_start_at) values('${id(40)}','${id(11)}','${id(2)}','${id(20)}','confirmed',now()+interval '3 days',null);`);
 const auth=async(uid,role="authenticated")=>db.exec(`select set_config('test.uid','${uid}',false),set_config('test.role','${role}',false);`);
 await auth(id(1));
 await db.query("select set_doctor_specialties($1,$2)",[id(11),[id(30)]]);
 await db.query("select authorize_doctor_signature($1,$2)",[id(11),"data:image/png;base64,example"]);
 const document=(await db.query(`insert into medical_documents(doctor_id,patient_id,clinic_id,appointment_id,status,signature_status,released_to_patient) values('${id(11)}','${id(2)}','${id(20)}','${id(40)}','issued','signed',true) returning *`)).rows[0];
 assert.equal(document.status,"draft");assert.equal(document.signature_status,"pending");assert.equal(document.released_to_patient,false);assert.equal(document.identity_snapshot.patient.full_name,"Paciente Privado");
 await assert.rejects(db.query("update medical_documents set status='issued',signature_status='signed' where id=$1",[document.id]));
 await assert.rejects(db.query("update medical_documents set certification_required=false where id=$1",[document.id]));
 await db.query("update medical_documents set status='cancelled' where id=$1",[document.id]);
 assert.equal((await db.query("select released_to_patient from medical_documents where id=$1",[document.id])).rows[0].released_to_patient,false);
 await auth(id(3));await assert.rejects(db.query("select authorize_doctor_signature($1,$2)",[id(11),"data:image/png;base64,forged"]));await assert.rejects(db.query("select set_doctor_specialties($1,$2)",[id(11),[id(30)]]));
 await assert.rejects(db.query(`insert into medical_documents(doctor_id,patient_id,clinic_id,appointment_id) values('${id(11)}','${id(2)}','${id(20)}','${id(40)}')`));
 await auth(id(2));await assert.rejects(db.query("select submit_care_review($1,'doctor',5,'ótimo',true)",[id(40)]));
 await db.exec(`update appointments set status='completed' where id='${id(40)}'`);
 await db.query("select submit_care_review($1,'doctor',5,'ótimo',true)",[id(40)]);
 await assert.rejects(db.query("select submit_care_review($1,'doctor',4,'outra',false)",[id(40)]));
 const reviews=(await db.query("select * from read_care_reviews('doctor',$1)",[id(11)])).rows;
 assert.equal(reviews[0].author_name,"Avaliação anônima");assert.ok(!('author_id' in reviews[0]));assert.ok(!('appointment_id' in reviews[0]));
 await assert.rejects(db.query("select * from read_care_reviews('patient',$1)",[id(2)]));
 await auth(id(1));await db.query("select submit_care_review($1,'patient',4,'',false)",[id(40)]);
 await auth(id(3));assert.equal((await db.query("select * from read_care_reviews('patient',$1)",[id(2)])).rows.length,1);
 await auth(id(1));await assert.rejects(db.query("select submit_care_review($1,'patient',4,'Diagnóstico não permitido',false)",[id(40)]));
 assert.equal((await db.query("select count(*)::int as n from appointment_outbox")).rows[0].n,4);
 const first=(await db.query("select * from claim_appointment_messages()")).rows;const second=(await db.query("select * from claim_appointment_messages()")).rows;assert.equal(first.length,2);assert.equal(second.length,0);
 for(let i=0;i<20;i++)assert.equal((await db.query("select consume_discovery_quota() as allowed")).rows[0].allowed,true);
 assert.equal((await db.query("select consume_discovery_quota() as allowed")).rows[0].allowed,false);
 await db.exec(`update doctors set clinic_id='${id(20)}',average_consultation_minutes=30,accepts_private_consultation=true;update clinics set is_active=true,accepts_private_consultation=true;insert into doctor_availability select '${id(11)}',true,n,n,'08:00'::time,'18:00'::time,30 from generate_series(0,6)n;`);
 await auth(id(2));
 const slots=(await db.query("select * from get_doctor_booking_slots($1,$2)",[id(11),id(30)])).rows;
 assert.ok(slots.length>0);const slot=slots[0];
 const booked=(await db.query("select request_doctor_booking($1,$2,$3) as id",[id(11),id(30),slot.start_at])).rows[0];assert.ok(booked.id);
 await assert.rejects(db.query("select request_doctor_booking($1,$2,$3)",[id(11),id(30),slot.start_at]));
 await assert.rejects(db.query(`insert into appointments(id,doctor_id,patient_id,clinic_id,status,requested_start_at,requested_end_at) values('${id(99)}','${id(11)}','${id(2)}','${id(20)}','pending',$1,$2)`,[slot.start_at,slot.end_at]));
 await auth(id(2));await db.exec('set role authenticated');assert.equal((await db.query("select * from doctor_signatures")).rows.length,0);await db.exec('reset role');
 }finally{await db.close();}
});
