"use client";
import {useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
export default function ClinicalHistorySharing(){
 const [doctors,setDoctors]=useState<{id:string;name:string}[]>([]);const [grants,setGrants]=useState<{doctor_id:string;expires_at:string}[]>([]);const [selected,setSelected]=useState("");const [message,setMessage]=useState("");const [revision,setRevision]=useState(0);const [busy,setBusy]=useState(false);const [consent,setConsent]=useState(false);
 useEffect(()=>{let alive=true;void(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [appointments,permissions,prefs]=await Promise.all([supabase.from("appointments").select("doctors(id,name)").eq("patient_id",user.id),supabase.from("clinical_history_grants").select("doctor_id,expires_at").eq("patient_id",user.id),supabase.from("patient_preferences").select("clinical_ai_consent").eq("patient_id",user.id).maybeSingle()]);if(!alive)return;if(appointments.error||permissions.error||prefs.error){setMessage("Não foi possível carregar as permissões do histórico.");return;}setDoctors([...new Map((appointments.data||[]).map(a=>Array.isArray(a.doctors)?a.doctors[0]:a.doctors).filter(Boolean).map(d=>[d.id,d])).values()]);setGrants(permissions.data||[]);setConsent(prefs.data?.clinical_ai_consent||false);})();return()=>{alive=false;};},[revision]);
 async function change(doctorId:string,revoke=false){setBusy(true);const {data:{user}}=await supabase.auth.getUser();if(user){const result=revoke?await supabase.from("clinical_history_grants").delete().eq("patient_id",user.id).eq("doctor_id",doctorId):await supabase.from("clinical_history_grants").upsert({patient_id:user.id,doctor_id:doctorId,expires_at:new Date(Date.now()+30*86400000).toISOString()},{onConflict:"patient_id,doctor_id"});setMessage(result.error?"Não foi possível alterar a autorização.":revoke?"Acesso revogado.":"Acesso ao histórico autorizado por 30 dias.");setRevision(n=>n+1);}setBusy(false);}
 async function saveConsent(){setBusy(true);const {data:{user}}=await supabase.auth.getUser();if(user){const result=await supabase.from("patient_preferences").upsert({patient_id:user.id,clinical_ai_consent:consent,consent_updated_at:new Date().toISOString()},{onConflict:"patient_id"});setMessage(result.error?"Não foi possível salvar.":"Preferência salva. A geração depende da ativação do serviço e da revisão médica.");}setBusy(false);}
 return <section className="mn-panel mb-6 space-y-4"><h2 className="text-xl font-semibold">Quem pode consultar meu histórico</h2><p className="text-sm">Autorize um médico dos seus atendimentos a acessar consultas anteriores por 30 dias. Você pode revogar o acesso a qualquer momento; isso não apaga os registros dos atendimentos que o profissional realizou.</p><label className="block text-sm font-semibold">Médico<select className="app-input mt-2" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecione um médico</option>{doctors.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><button className="mn-button-secondary" disabled={busy||!selected} onClick={()=>void change(selected)}>Autorizar por 30 dias</button>{grants.map(g=><p className="text-sm" key={g.doctor_id}>{doctors.find(d=>d.id===g.doctor_id)?.name||"Médico"} · até {new Date(g.expires_at).toLocaleDateString("pt-BR")} <button className="ml-3 underline" disabled={busy} onClick={()=>void change(g.doctor_id,true)}>Revogar</button></p>)}<div className="border-t border-mn-border pt-4"><label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Autorizo o processamento dos registros das consultas pelo serviço de IA para elaborar resumos auxiliares, sujeitos à conferência médica. Os registros originais serão preservados.</label><p className="mt-2 text-xs text-mn-graphite/60">Quando ativado, o serviço utiliza a API da OpenAI. Dados clínicos continuam sensíveis mesmo sem nome e CPF. A revogação impede novas gerações; resumos já incorporados ao histórico são preservados.</p><button className="mn-button-secondary mt-3" disabled={busy} onClick={()=>void saveConsent()}>Salvar preferência de IA</button></div>{message&&<p role="status" className="text-sm">{message}</p>}</section>;
}
