"use client";
import { useEffect,useState } from "react";
import AddressLookup from "./address-lookup";
import { supabase } from "../lib/supabase";
import { geocodeBrazilAddress } from "../lib/geocode";
const fields={address_zipcode:"CEP",address_street:"Logradouro",address_number:"Número",address_complement:"Complemento",address_neighborhood:"Bairro",address_city:"Cidade",address_state:"UF"};
type Address=Record<keyof typeof fields,string>;
export default function DoctorOffice({doctorId}:{doctorId:string}){const [form,setForm]=useState<Address>({address_zipcode:"",address_street:"",address_number:"",address_complement:"",address_neighborhood:"",address_city:"",address_state:""});const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");useEffect(()=>{let alive=true;void supabase.from("doctors").select("*").eq("id",doctorId).maybeSingle().then(({data})=>{if(alive&&data)setForm(Object.fromEntries(Object.keys(fields).map(k=>[k,data[k]||""])) as Address);});return()=>{alive=false;};},[doctorId]);
async function save(){if(!form.address_street.trim()||!form.address_city.trim()||!/^[A-Z]{2}$/.test(form.address_state)){setMessage("Preencha logradouro, cidade e UF.");return;}setBusy(true);try{const location=await geocodeBrazilAddress({zipcode:form.address_zipcode,street:form.address_street,number:form.address_number,neighborhood:form.address_neighborhood,city:form.address_city,state:form.address_state});const {error}=await supabase.from("doctors").update({...form,latitude:location.latitude,longitude:location.longitude}).eq("id",doctorId).select("id").single();if(error)throw error;setMessage(location.latitude!==null?"Endereço profissional salvo. Confira o destino ao abrir o mapa.":"Endereço salvo. Coordenadas não localizadas; a navegação utilizará o endereço informado.");}catch{setMessage("Não foi possível salvar o endereço profissional.");}finally{setBusy(false);}}
return <section className="mn-panel mt-6 space-y-4"><h2 className="text-xl font-semibold">Endereço do consultório</h2><p className="text-sm text-slate-500">Endereço profissional para atendimentos sem vínculo com clínica. Para consultas em uma clínica, será utilizado o endereço da unidade.</p><AddressLookup onAddress={a=>setForm({address_zipcode:a.zipcode,address_street:a.street,address_number:a.number||"",address_complement:"",address_neighborhood:a.neighborhood,address_city:a.city,address_state:a.state})}/><div className="grid gap-3 sm:grid-cols-2">{Object.entries(fields).map(([key,label])=><label key={key} className="text-sm font-medium">{label}<input className="mn-input mt-1" value={form[key as keyof Address]} maxLength={key==="address_state"?2:150} onChange={e=>setForm({...form,[key]:key==="address_state"?e.target.value.toUpperCase():e.target.value})}/></label>)}</div><button type="button" className="mn-button" disabled={busy} onClick={()=>void save()}>{busy?"Salvando…":"Salvar endereço profissional"}</button>{message&&<p role="status" className="text-sm">{message}</p>}</section>;}
