"use client";
import {useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
type Contact={id:string;name:string;phone:string;address:string;specialty:string;website:string};
const empty={name:"",phone:"",address:"",specialty:"",website:""};
export default function ExternalContacts(){
 const [contacts,setContacts]=useState<Contact[]>([]),[form,setForm]=useState(empty),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{let alive=true;void supabase.from("external_care_contacts").select("id,name,phone,address,specialty,website").order("name").then(r=>{if(alive){if(r.error)setMessage("Não foi possível carregar seus contatos.");else setContacts(r.data||[]);}});return()=>{alive=false;};},[revision]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);const r=await supabase.from("external_care_contacts").insert(form);setMessage(r.error?"Não foi possível salvar. Confira os campos e use HTTPS no site.":"Contato salvo na sua agenda pessoal.");if(!r.error){setForm(empty);setRevision(n=>n+1);}setBusy(false);}
 async function remove(id:string){setBusy(true);const r=await supabase.from("external_care_contacts").delete().eq("id",id);setMessage(r.error?"Não foi possível excluir.":"Contato excluído.");setRevision(n=>n+1);setBusy(false);}
 return <section className="mn-panel mt-8"><h2 className="text-xl font-semibold">Meus contatos externos</h2><p className="mt-2 text-sm">Cadastre os contatos que você já conhece. Eles ficam visíveis somente para você e não oferecem agendamento pela MediNexus.</p><details className="mt-4"><summary className="cursor-pointer font-semibold text-mn-teal">Cadastrar um contato</summary><form onSubmit={save} className="mt-4 grid gap-3 sm:grid-cols-2">{([['name','Nome',160],['phone','Telefone',40],['specialty','Especialidade',120],['address','Endereço',400],['website','Site HTTPS (opcional)',500]] as const).map(([key,label,max])=><label key={key} className="text-sm font-semibold">{label}<input className="mn-input mt-1" type={key==='website'?'url':'text'} required={key==='name'} minLength={key==='name'?2:undefined} maxLength={max} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<button disabled={busy} className="mn-button self-end">Salvar contato</button></form></details>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}<div className="mt-4 grid gap-3 md:grid-cols-2">{contacts.map(c=><article key={c.id} className="rounded-xl border border-mn-border p-4"><h3 className="font-semibold">{c.name}</h3><p className="text-sm">{c.specialty}</p><p className="mt-1 text-sm">{c.address}</p><div className="mt-3 flex flex-wrap gap-4 text-sm">{c.phone&&<a className="underline" href={`tel:${c.phone.replace(/[^+0-9]/g,'')}`}>{c.phone}</a>}{c.website&&/^https:\/\//.test(c.website)&&<a className="underline" href={c.website} target="_blank" rel="noopener noreferrer">Site</a>}<button disabled={busy} className="underline" onClick={()=>void remove(c.id)}>Excluir</button></div></article>)}</div></section>;
}
