"use client";
import { useEffect, useState } from "react";
import { Star } from "lucide-react";
import { supabase } from "../lib/supabase";

type Review = { id: string; rating: number; comment: string; author_name: string; created_at: string };
export function Reviews({ kind, targetId }: { kind: "doctor" | "clinic" | "patient"; targetId: string }) {
  const [reviews, setReviews] = useState<Review[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let alive=true; void supabase.rpc("read_care_reviews",{p_target_kind:kind,p_target_id:targetId}).then(({data,error})=>{if(alive){setReviews(data||[]);setLoading(false);if(error)setError("Avaliações indisponíveis no momento.");}});return()=>{alive=false;};},[kind,targetId]);
  const average=reviews.length ? (reviews.reduce((sum,r)=>sum+r.rating,0)/reviews.length).toFixed(1) : null;
  return <section className="mn-panel"><div className="flex items-center justify-between gap-4"><div><p className="mn-eyebrow">Experiências de atendimento</p><h2 className="text-2xl font-semibold">Avaliações {kind==="patient" ? "na área médica" : "da comunidade"}</h2></div>{average&&<p className="flex items-center gap-2 text-2xl font-semibold"><Star className="fill-mn-purple text-mn-purple"/>{average}<span className="text-xs text-slate-500">({reviews.length})</span></p>}</div>
    {loading?<p role="status" className="mt-4 text-sm">Carregando avaliações…</p>:error?<p role="status" className="mt-4 text-sm">{error}</p>:!reviews.length?<p className="mt-4 text-sm text-slate-500">Ainda não há avaliações de consultas concluídas.</p>:<div className="mt-5 divide-y divide-mn-border">{reviews.map(r=><article className="py-4" key={r.id}><div className="flex justify-between gap-3 text-sm"><strong>{r.author_name}</strong><span aria-label={`${r.rating} de 5 estrelas`} className="text-mn-purple">{"★".repeat(r.rating)}{"☆".repeat(5-r.rating)}</span></div>{r.comment&&<p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{r.comment}</p>}<p className="mt-2 text-xs text-slate-400">Consulta verificada · {new Date(r.created_at).toLocaleDateString("pt-BR")}</p></article>)}</div>}
  </section>;
}
export function ReviewForm({ appointmentId, kind }: { appointmentId: string; kind: "doctor" | "clinic" | "patient" }) {
  const [open,setOpen]=useState(false);const [rating,setRating]=useState(0);const [comment,setComment]=useState("");const [anonymous,setAnonymous]=useState(true);const [busy,setBusy]=useState(false);const [sent,setSent]=useState(false);const [message,setMessage]=useState("");
  async function submit(){if(!rating){setMessage("Escolha uma nota de 1 a 5.");return;}setBusy(true);const r=await supabase.rpc("submit_care_review",{p_appointment_id:appointmentId,p_target_kind:kind,p_rating:rating,p_comment:comment,p_anonymous:anonymous});setBusy(false);setMessage(r.error ? r.error.code==="23505" ? "Você já avaliou este atendimento." : "Não foi possível enviar a avaliação. Verifique se a consulta foi concluída." : "Avaliação publicada com sucesso.");if(!r.error)setSent(true);}
  const label=kind==="doctor"?"médico":kind==="clinic"?"clínica":"paciente";
  return <div><button type="button" className="mn-button-secondary" aria-expanded={open} onClick={()=>setOpen(!open)}><Star size={16}/>Avaliar {label}</button>{open&&<div className="mt-3 max-w-xl rounded-2xl border border-mn-border bg-white p-5"><h3 className="font-semibold">Como foi o atendimento?</h3><p className="my-2 text-xs leading-5 text-slate-500">{kind==="patient"?"Nota sobre pontualidade e comunicação, visível apenas para médicos cadastrados. Não descreva diagnósticos ou informações clínicas.":"Sua avaliação será pública. Não inclua documentos, telefone ou informações de saúde."}</p><div className="my-3 flex gap-2" role="group" aria-label="Nota">{[1,2,3,4,5].map(n=><button key={n} type="button" disabled={sent} aria-label={`${n} estrela${n>1?"s":""}`} aria-pressed={rating===n} onClick={()=>setRating(n)} className="rounded-lg p-2"><Star className={n<=rating?"fill-mn-purple text-mn-purple":"text-slate-300"}/></button>)}</div>{kind!=="patient"&&<textarea className="mn-input" aria-label="Comentário sobre atendimento" maxLength={1200} rows={3} value={comment} disabled={sent} onChange={e=>setComment(e.target.value)} placeholder="Compartilhe sua experiência (opcional)"/>}<label className="my-3 flex gap-2 text-sm"><input type="checkbox" checked={anonymous} disabled={sent} onChange={e=>setAnonymous(e.target.checked)}/>Ocultar meu nome na avaliação</label><button type="button" className="mn-button" disabled={busy||sent} onClick={()=>void submit()}>{busy?"Enviando…":sent?"Avaliação enviada":"Enviar avaliação"}</button>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</div>}</div>;
}
